In [2]:
from re import X
import pygame
import numpy as np


pygame 2.1.2 (SDL 2.0.20, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [3]:
class Point():
    def __init__(self, x, y):
        self.vec = np.matrix([[x], [y]])

    def vecprod(self, matrix):
        A.vec = A.vec @ matrix
        return self




In [13]:
def translation_matrix(tx, ty):
    translation_matrix = np.matrix([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1]])
    return translation_matrix

vec = np.matrix([[2,2,2]]).reshape(3,1)
translation_matrix(1,1)@vec


matrix([[4],
        [4],
        [2]])

### Wheel

In [5]:
WHITE = (255, 255, 255)
RED = (255, 0, 0)
BLACK = (0, 0, 0)

WIDTH, HEIGHT = 800, 600
screen_center = [WIDTH/2, HEIGHT/2]  # x, y

# pygame.display.set_caption("3D projection Lab#2")
# screen = pygame.display.set_mode((WIDTH, HEIGHT))


In [6]:
class Point():
    def __init__(self, x, y):
        self.vec = np.matrix([[x], [y]])
        self.x = self.vec[0, 0]
        self.y = self.vec[1, 0]

    def vecprod(self, matrix):
        self.vec = matrix @ self.vec
        self.x = self.vec[0, 0]
        self.y = self.vec[1, 0]
        return self


In [7]:
Scale = np.matrix([[2, 0],
                   [0, 2]])


A = Point(10, 20)
print(A.vec, 'Before vecprod\n')
A.vecprod(Scale)
print(A.vec, '\n')
A.x
# print()


[[10]
 [20]] Before vecprod

[[20]
 [40]] 



20

In [8]:



class Wheel:
    def __init__(self, radius, x=screen_center[0], y=screen_center[1], color='black'):
        
        self.radius = radius
        self.diag_coef = radius/np.sqrt(2)
        self.color = color

        self.center = Point(x, y)

    def drawline(self, point1, point2):
        # tuple1 = (point1.vec[0, 0], point1.vec[0, 1])
        # tuple2 = (point2.vec[0, 0], point2.vec[0, 1])
        pygame.draw.line(screen, BLACK, point1.vec[0, 0],\
             point1.vec[1, 0], point2.vec[0, 0], point2.vec[1, 0])

    def draw(self):
        pass
    
        

In [9]:
wheel = Wheel(5, 10,20)
wheel.center.vec[1,0]

20

In [10]:
projection_matrix = np.matrix([
    [1, 0, 0],
    [0, 1, 0]
])


x = screen_center[0]
y = screen_center[1]

# pygame.draw.circle(screen, BLACK, (x,y), 5)

In [11]:
# clock = pygame.time.Clock()
# while True:

#     clock.tick(60)

#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             exit()
#         if event.type == pygame.KEYDOWN:
#             if event.key == pygame.K_ESCAPE:
#                 pygame.quit()
#                 exit()

#     # update stuff
#     screen.fill(WHITE)

#     # drawining stuff

#     pygame.display.update()
